// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/pokt-foundation/dwh-client/client"

	mock "github.com/stretchr/testify/mock"
)

// IDWHClient is an autogenerated mock type for the IDWHClient type
type IDWHClient struct {
	mock.Mock
}

// GetTotalRelaysForPortalAppIDs provides a mock function with given fields: ctx, params
func (_m *IDWHClient) GetTotalRelaysForPortalAppIDs(ctx context.Context, params client.GetTotalRelaysForPortalAppIDsParams) ([]client.AnalyticsRelaysTotal, error) {
	ret := _m.Called(ctx, params)

	var r0 []client.AnalyticsRelaysTotal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.GetTotalRelaysForPortalAppIDsParams) ([]client.AnalyticsRelaysTotal, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.GetTotalRelaysForPortalAppIDsParams) []client.AnalyticsRelaysTotal); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.AnalyticsRelaysTotal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.GetTotalRelaysForPortalAppIDsParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIDWHClient creates a new instance of IDWHClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDWHClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDWHClient {
	mock := &IDWHClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
