name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      version: ${{ steps.semantic.outputs.release-version }}

    steps:
      - uses: actions/checkout@v3

      - name: Tag Semantic Release Version
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          branches: |
            [
              'main'
            ]
          extra_plugins: |
            @semantic-release/commit-analyzer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Go List
        if: steps.semantic.outputs.new-release-published == 'true'
        run: GOPROXY=proxy.golang.org go list -m github.com/pokt-foundation/dwh-client@v${{ steps.semantic.outputs.release-version }}
